// Curated line icons for the project icon picker. Explicit named imports keep this tree-shakeable.
import type { LucideIcon } from 'lucide-react'
import {
  Briefcase,
  Rocket,
  Target,
  Lightbulb,
  BookOpen,
  Book,
  Calendar,
  Camera,
  ChartBar,
  ChartLine,
  ChartPie,
  Check,
  CircleCheck,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  CreditCard,
  Database,
  Flag,
  Flame,
  Folder,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  House,
  Image,
  Inbox,
  Key,
  Layers,
  Layout,
  LayoutDashboard,
  Leaf,
  Link,
  Lock,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Mic,
  Moon,
  Music,
  Newspaper,
  Package,
  Palette,
  Paperclip,
  Pen,
  Pencil,
  Phone,
  Plane,
  PieChart,
  Puzzle,
  Receipt,
  Rss,
  Scale,
  Search,
  Settings,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Sparkles,
  Star,
  Sun,
  Tag,
  Terminal,
  ThumbsUp,
  Ticket,
  Timer,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  User,
  Users,
  Video,
  Wallet,
  Wand,
  Wifi,
  Wrench,
  Zap,
  Anchor,
  Award,
  Bell,
  Bookmark,
  Bug,
  Building,
  Bus,
  Car,
  Clipboard,
  ClipboardList,
  Cpu,
  Crown,
  Diamond,
  Dumbbell,
  Eye,
  FileText,
  Fingerprint,
  Gamepad,
  Gauge,
  Handshake,
  Hash,
  Headphones,
  Hotel,
  Landmark,
  Languages,
  ListChecks,
  Luggage,
  Medal,
  Microscope,
  Mountain,
  Notebook,
  Percent,
  PiggyBank,
  Presentation,
  Shield,
  Ship,
  Store,
  Sword,
  Tent,
  TrendingUp,
  Wine,
  Utensils,
  Train,
  Bike,
  Banknote,
  Brain,
  Calculator,
  Hammer,
  Lamp,
  Plug,
  Stethoscope,
  Sprout,
  Flower,
  Trees,
  TreePine,
  Cat,
  Dog,
  Fish,
  Bird,
  Bone,
  Baby,
  Apple,
  Cherry,
  Pizza,
  Cake,
  Candy,
  IceCream,
  Beer,
} from 'lucide-react'

export const PROJECT_ICONS: Record<string, LucideIcon> = {
  'briefcase': Briefcase,
  'rocket': Rocket,
  'target': Target,
  'lightbulb': Lightbulb,
  'book-open': BookOpen,
  'book': Book,
  'calendar': Calendar,
  'camera': Camera,
  'chart-bar': ChartBar,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'check': Check,
  'circle-check': CircleCheck,
  'clock': Clock,
  'cloud': Cloud,
  'code': Code,
  'coffee': Coffee,
  'compass': Compass,
  'credit-card': CreditCard,
  'database': Database,
  'flag': Flag,
  'flame': Flame,
  'folder': Folder,
  'gift': Gift,
  'globe': Globe,
  'graduation-cap': GraduationCap,
  'heart': Heart,
  'house': House,
  'image': Image,
  'inbox': Inbox,
  'key': Key,
  'layers': Layers,
  'layout': Layout,
  'layout-dashboard': LayoutDashboard,
  'leaf': Leaf,
  'link': Link,
  'lock': Lock,
  'mail': Mail,
  'map': Map,
  'map-pin': MapPin,
  'megaphone': Megaphone,
  'message-circle': MessageCircle,
  'messages-square': MessagesSquare,
  'mic': Mic,
  'moon': Moon,
  'music': Music,
  'newspaper': Newspaper,
  'package': Package,
  'palette': Palette,
  'paperclip': Paperclip,
  'pen': Pen,
  'pencil': Pencil,
  'phone': Phone,
  'plane': Plane,
  'pie-chart': PieChart,
  'puzzle': Puzzle,
  'receipt': Receipt,
  'rss': Rss,
  'scale': Scale,
  'search': Search,
  'settings': Settings,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'smile': Smile,
  'sparkles': Sparkles,
  'star': Star,
  'sun': Sun,
  'tag': Tag,
  'terminal': Terminal,
  'thumbs-up': ThumbsUp,
  'ticket': Ticket,
  'timer': Timer,
  'trophy': Trophy,
  'truck': Truck,
  'tv': Tv,
  'umbrella': Umbrella,
  'user': User,
  'users': Users,
  'video': Video,
  'wallet': Wallet,
  'wand': Wand,
  'wifi': Wifi,
  'wrench': Wrench,
  'zap': Zap,
  'anchor': Anchor,
  'award': Award,
  'bell': Bell,
  'bookmark': Bookmark,
  'bug': Bug,
  'building': Building,
  'bus': Bus,
  'car': Car,
  'clipboard': Clipboard,
  'clipboard-list': ClipboardList,
  'cpu': Cpu,
  'crown': Crown,
  'diamond': Diamond,
  'dumbbell': Dumbbell,
  'eye': Eye,
  'file-text': FileText,
  'fingerprint': Fingerprint,
  'gamepad': Gamepad,
  'gauge': Gauge,
  'handshake': Handshake,
  'hash': Hash,
  'headphones': Headphones,
  'hotel': Hotel,
  'landmark': Landmark,
  'languages': Languages,
  'list-checks': ListChecks,
  'luggage': Luggage,
  'medal': Medal,
  'microscope': Microscope,
  'mountain': Mountain,
  'notebook': Notebook,
  'percent': Percent,
  'piggy-bank': PiggyBank,
  'presentation': Presentation,
  'shield': Shield,
  'ship': Ship,
  'store': Store,
  'sword': Sword,
  'tent': Tent,
  'trending-up': TrendingUp,
  'wine': Wine,
  'utensils': Utensils,
  'train': Train,
  'bike': Bike,
  'banknote': Banknote,
  'brain': Brain,
  'calculator': Calculator,
  'hammer': Hammer,
  'lamp': Lamp,
  'plug': Plug,
  'stethoscope': Stethoscope,
  'sprout': Sprout,
  'flower': Flower,
  'trees': Trees,
  'tree-pine': TreePine,
  'cat': Cat,
  'dog': Dog,
  'fish': Fish,
  'bird': Bird,
  'bone': Bone,
  'baby': Baby,
  'apple': Apple,
  'cherry': Cherry,
  'pizza': Pizza,
  'cake': Cake,
  'candy': Candy,
  'ice-cream': IceCream,
  'beer': Beer,
}

export const PROJECT_ICON_NAMES = Object.keys(PROJECT_ICONS)
